elasticsearchHosts: "http://elasticsearch-master.logging.svc.cluster.local:9200"

service:
  type: LoadBalancer

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "300m"
    memory: "512Mi"